/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as DomesticRouteImport } from './routes/domestic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as FlightsIndexRouteImport } from './routes/flights.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HotelsReviewRouteImport } from './routes/hotels.review'
import { Route as HotelsDetailRouteImport } from './routes/hotels.detail'
import { Route as HotelsConfirmationRouteImport } from './routes/hotels.confirmation'
import { Route as HotelsCheckoutRouteImport } from './routes/hotels.checkout'
import { Route as FlightsReviewRouteImport } from './routes/flights.review'
import { Route as FlightsConfirmationRouteImport } from './routes/flights.confirmation'
import { Route as FlightsCheckoutRouteImport } from './routes/flights.checkout'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFunnelRouteImport } from './routes/admin.funnel'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountTravellersRouteImport } from './routes/_authenticated/account.travellers'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountBookingsRouteImport } from './routes/_authenticated/account.bookings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticRoute = DomesticRouteImport.update({
  id: '/domestic',
  path: '/domestic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsReviewRoute = HotelsReviewRouteImport.update({
  id: '/hotels/review',
  path: '/hotels/review',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsDetailRoute = HotelsDetailRouteImport.update({
  id: '/hotels/detail',
  path: '/hotels/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsConfirmationRoute = HotelsConfirmationRouteImport.update({
  id: '/hotels/confirmation',
  path: '/hotels/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsCheckoutRoute = HotelsCheckoutRouteImport.update({
  id: '/hotels/checkout',
  path: '/hotels/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsReviewRoute = FlightsReviewRouteImport.update({
  id: '/flights/review',
  path: '/flights/review',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsConfirmationRoute = FlightsConfirmationRouteImport.update({
  id: '/flights/confirmation',
  path: '/flights/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsCheckoutRoute = FlightsCheckoutRouteImport.update({
  id: '/flights/checkout',
  path: '/flights/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFunnelRoute = AdminFunnelRouteImport.update({
  id: '/admin/funnel',
  path: '/admin/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTravellersRoute =
  AuthenticatedAccountTravellersRouteImport.update({
    id: '/travellers',
    path: '/travellers',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountBookingsRoute =
  AuthenticatedAccountBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/international': typeof InternationalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/funnel': typeof AdminFunnelRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/checkout': typeof FlightsCheckoutRoute
  '/flights/confirmation': typeof FlightsConfirmationRoute
  '/flights/review': typeof FlightsReviewRoute
  '/hotels/checkout': typeof HotelsCheckoutRoute
  '/hotels/confirmation': typeof HotelsConfirmationRoute
  '/hotels/detail': typeof HotelsDetailRoute
  '/hotels/review': typeof HotelsReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/travellers': typeof AuthenticatedAccountTravellersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/international': typeof InternationalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/funnel': typeof AdminFunnelRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/checkout': typeof FlightsCheckoutRoute
  '/flights/confirmation': typeof FlightsConfirmationRoute
  '/flights/review': typeof FlightsReviewRoute
  '/hotels/checkout': typeof HotelsCheckoutRoute
  '/hotels/confirmation': typeof HotelsConfirmationRoute
  '/hotels/detail': typeof HotelsDetailRoute
  '/hotels/review': typeof HotelsReviewRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/flights': typeof FlightsIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/travellers': typeof AuthenticatedAccountTravellersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/international': typeof InternationalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/funnel': typeof AdminFunnelRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/flights/checkout': typeof FlightsCheckoutRoute
  '/flights/confirmation': typeof FlightsConfirmationRoute
  '/flights/review': typeof FlightsReviewRoute
  '/hotels/checkout': typeof HotelsCheckoutRoute
  '/hotels/confirmation': typeof HotelsConfirmationRoute
  '/hotels/detail': typeof HotelsDetailRoute
  '/hotels/review': typeof HotelsReviewRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/flights/': typeof FlightsIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/_authenticated/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/travellers': typeof AuthenticatedAccountTravellersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/domestic'
    | '/international'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/funnel'
    | '/admin/login'
    | '/admin/sessions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/flights/checkout'
    | '/flights/confirmation'
    | '/flights/review'
    | '/hotels/checkout'
    | '/hotels/confirmation'
    | '/hotels/detail'
    | '/hotels/review'
    | '/admin/'
    | '/blog/'
    | '/flights/'
    | '/hotels/'
    | '/account/bookings'
    | '/account/profile'
    | '/account/travellers'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/domestic'
    | '/international'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/funnel'
    | '/admin/login'
    | '/admin/sessions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/flights/checkout'
    | '/flights/confirmation'
    | '/flights/review'
    | '/hotels/checkout'
    | '/hotels/confirmation'
    | '/hotels/detail'
    | '/hotels/review'
    | '/admin'
    | '/blog'
    | '/flights'
    | '/hotels'
    | '/account/bookings'
    | '/account/profile'
    | '/account/travellers'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/domestic'
    | '/international'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/account'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/funnel'
    | '/admin/login'
    | '/admin/sessions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/flights/checkout'
    | '/flights/confirmation'
    | '/flights/review'
    | '/hotels/checkout'
    | '/hotels/confirmation'
    | '/hotels/detail'
    | '/hotels/review'
    | '/admin/'
    | '/blog/'
    | '/flights/'
    | '/hotels/'
    | '/_authenticated/account/bookings'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/travellers'
    | '/_authenticated/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DomesticRoute: typeof DomesticRoute
  InternationalRoute: typeof InternationalRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFunnelRoute: typeof AdminFunnelRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FlightsCheckoutRoute: typeof FlightsCheckoutRoute
  FlightsConfirmationRoute: typeof FlightsConfirmationRoute
  FlightsReviewRoute: typeof FlightsReviewRoute
  HotelsCheckoutRoute: typeof HotelsCheckoutRoute
  HotelsConfirmationRoute: typeof HotelsConfirmationRoute
  HotelsDetailRoute: typeof HotelsDetailRoute
  HotelsReviewRoute: typeof HotelsReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic': {
      id: '/domestic'
      path: '/domestic'
      fullPath: '/domestic'
      preLoaderRoute: typeof DomesticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/': {
      id: '/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/review': {
      id: '/hotels/review'
      path: '/hotels/review'
      fullPath: '/hotels/review'
      preLoaderRoute: typeof HotelsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/detail': {
      id: '/hotels/detail'
      path: '/hotels/detail'
      fullPath: '/hotels/detail'
      preLoaderRoute: typeof HotelsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/confirmation': {
      id: '/hotels/confirmation'
      path: '/hotels/confirmation'
      fullPath: '/hotels/confirmation'
      preLoaderRoute: typeof HotelsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/checkout': {
      id: '/hotels/checkout'
      path: '/hotels/checkout'
      fullPath: '/hotels/checkout'
      preLoaderRoute: typeof HotelsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/review': {
      id: '/flights/review'
      path: '/flights/review'
      fullPath: '/flights/review'
      preLoaderRoute: typeof FlightsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/confirmation': {
      id: '/flights/confirmation'
      path: '/flights/confirmation'
      fullPath: '/flights/confirmation'
      preLoaderRoute: typeof FlightsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/checkout': {
      id: '/flights/checkout'
      path: '/flights/checkout'
      fullPath: '/flights/checkout'
      preLoaderRoute: typeof FlightsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/funnel': {
      id: '/admin/funnel'
      path: '/admin/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AdminFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/travellers': {
      id: '/_authenticated/account/travellers'
      path: '/travellers'
      fullPath: '/account/travellers'
      preLoaderRoute: typeof AuthenticatedAccountTravellersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/bookings': {
      id: '/_authenticated/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AuthenticatedAccountBookingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBookingsRoute: typeof AuthenticatedAccountBookingsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountTravellersRoute: typeof AuthenticatedAccountTravellersRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBookingsRoute: AuthenticatedAccountBookingsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountTravellersRoute: AuthenticatedAccountTravellersRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DomesticRoute: DomesticRoute,
  InternationalRoute: InternationalRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFunnelRoute: AdminFunnelRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FlightsCheckoutRoute: FlightsCheckoutRoute,
  FlightsConfirmationRoute: FlightsConfirmationRoute,
  FlightsReviewRoute: FlightsReviewRoute,
  HotelsCheckoutRoute: HotelsCheckoutRoute,
  HotelsConfirmationRoute: HotelsConfirmationRoute,
  HotelsDetailRoute: HotelsDetailRoute,
  HotelsReviewRoute: HotelsReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  FlightsIndexRoute: FlightsIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
